color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.641549
  lightness: 0.938063
  rhythmicContrast: 0.958382
  saturation: 0.81331
layout_spectrum: 1
name: mimiscakes
typography_spectrum: 0.11790172290056944
